#ifndef YAGA_UTILITY_COMPILER
#define YAGA_UTILITY_COMPILER

#define PRAGMA(s) _Pragma(#s)

#ifdef _MSC_VER
#define PRAGMA_WARNING(s) PRAGMA(warning(s))
#define PRAGMA_WARNING_DISABLE(n) PRAGMA_WARNING(disable: n)
#define DISABLE_WARNINGS         \
  PRAGMA_WARNING(push)           \
  PRAGMA_WARNING_DISABLE(4005)   \
  PRAGMA_WARNING_DISABLE(4100)   \
  PRAGMA_WARNING_DISABLE(4127)   \
  PRAGMA_WARNING_DISABLE(4201)   \
  PRAGMA_WARNING_DISABLE(4244)   \
  PRAGMA_WARNING_DISABLE(4324)   \
  PRAGMA_WARNING_DISABLE(6001)   \
  PRAGMA_WARNING_DISABLE(6011)   \
  PRAGMA_WARNING_DISABLE(6031)   \
  PRAGMA_WARNING_DISABLE(6255)   \
  PRAGMA_WARNING_DISABLE(6258)   \
  PRAGMA_WARNING_DISABLE(6386)   \
  PRAGMA_WARNING_DISABLE(6387)   \
  PRAGMA_WARNING_DISABLE(26110)  \
  PRAGMA_WARNING_DISABLE(26439)  \
  PRAGMA_WARNING_DISABLE(26451)  \
  PRAGMA_WARNING_DISABLE(26495)  \
  PRAGMA_WARNING_DISABLE(26498)  \
  PRAGMA_WARNING_DISABLE(26812)
#define ENABLE_WARNINGS PRAGMA_WARNING(pop)
#else // gcc and clang
#define DISABLE_WARNINGS PRAGMA(GCC diagnostic ignored "-Wall")
#define ENABLE_WARNINGS  PRAGMA(GCC diagnostic pop)
#endif

#endif // !YAGA_UTILITY_COMPILER